[main]
# scan_start_menu = yes
# scan_desktop = yes
scan_env_path = no

[cmd/eabbr]
cmd = silentcmd ${env:EDITOR} "${env:USERHOME}\Local\File\file_cheatsheets\cheatsheet\abbreviation.cht"
[cmd/ealias]
cmd = silentcmd ${env:EDITOR} "${env:USERHOME}\Share\dotfiles.win\.config\alias.yaml" "${env:USERHOME}\Share\dotfiles\.config\alias.yaml"
[cmd/ebookmark]
cmd = silentcmd ${env:EDITOR} "${env:USERHOME}\Local\File\file_bookmarks"
[cmd/echeatsheet]
cmd = silentcmd ${env:EDITOR} "${env:USERHOME}\Local\File\file_cheatsheets"
[cmd/eespanso]
cmd = silentcmd ${env:EDITOR} "${env:USERHOME}\Share\dotfiles\.config\espanso"
[cmd/efavorites]
cmd = silentcmd ${env:EDITOR} "${env:USERHOME}\Share\datas\goldendict_favorites.xml"
[cmd/epet]
cmd = silentcmd ${env:EDITOR} "${env:USERHOME}\Share\dotfiles\.config\pet"
[cmd/esnippets]
cmd = silentcmd ${env:EDITOR} "${env:USERHOME}\Share\dotfiles\.config\Sublime-text\Packages\User\Snippets"
[cmd/ewebsearch]
cmd = silentcmd ${env:EDITOR} "${env:USERHOME}\Share\dotfiles.win\Scoop\keypirinha\Profile\User\websearch.ini" "${env:USERHOME}\Share\scripts\arch\web-search.sh"

## Windows
[cmd/epuzztools]
cmd = silentcmd ${env:EDITOR} "${env:USERHOME}\Share\projs\Keypirinha-PuzzTools ${env:USERHOME}\Share\scripts\arch\rofi-transform.sh"

## Remote
[cmd/github-search-rss]
cmd = silentcmd ${env:BROWSER} https://github.com/scillidan/github-search-rss/edit/main/src/RSS.ts
[cmd/rss-aggregator]
cmd = silentcmd ${env:BROWSER} https://github.com/scillidan/rss-aggregator-rss/edit/main/rss_aggregator.py
[cmd/startpage]
cmd = silentcmd ${env:BROWSER} https://github.com/scillidan/excalith-start-page/edit/main/data/settings.json
[cmd/actions]
cmd = silentcmd ${env:BROWSER} https://github.com/scillidan/actions

## Other
[cmd/nvim]
cmd = silentcmd wezterm-gui start nvim "${env:USERHOME}"
[cmd/wssh]
cmd = silentcmd wezterm ssh scillidan@arch

# [cmd/evscodium]
# cmd = silentcmd ${env:EDITOR} "${env:USERHOME}\Scoop\persist\vscodium\data\user-data\User"
# [cmd/obsi]
# cmd = silentcmd obsidian://actions-uri/omnisearch/open?vault=Vault&query={{*}}