[main]
# keyword = bkm
# comment_prefix = #
# max_desc_len = 20%
# files =
directories =
    ${env:USERHOME}/Local/File/bookmarks;
include = *.bkm
exclude = *_arch
# default_cmd =
# notify = true
# omit_scheme = true

[scheme/http]
cmd = ${env:BROWSER}

[scheme/https]
cmd = ${env:BROWSER}

[experimental]
# format_order = alpha_asc
# format_include =
# format_exclude =
# strip_trailing_slash = true