[main]
# keyword = cht
# comment_prefix = #;##
# max_desc_len = 20%
# files =
#     ~/.cheatsheet/example.cht
directories =
    ${env:USERHOME}\Share\files\cheatsheets;
include = *.cht
exclude = *_arch;*.bak;*.txt
# notify = true