[defaults]
# always_evaluate = true
# enable = true
# item_label = Convert Currency
# update_freq = daily
# input_cur = USD
# output_cur = CNY
# separators = to
# destination_separators = and
app_id = ${env:OPENEXCHANGERATES_API_KEY}