[app]
launch_at_startup = no
hotkey_run = Ctrl+Alt+K
ignored_packages = Bookmarks, Everything, FileZilla, GoogleTranslate, WebSuggest, Winamp, WinSCP

[gui]
always_on_top = no
escape_always_closes = yes
hide_on_focus_lost = yes
max_height = 25
theme = Vanta

[external]
config_editor = "${env:EDITOR}"
editor = "${env:EDITOR}"
web_browser = "${env:BROWSER}"
# terminal = "_alacritty_command"
file_explorer = "dopus" {{file}}

[theme/Vanta]
opacity_back = 100
satellite_show = never
satellite_pos = topleft
satellite_size = small
control_margin = 3
textbox_padding = 3
listitem_padding = 1
layout = list_selmark,list_icon
color_background = #000000
color_foreground = #f8fafc
color_title = #f8fafc
color_textbox_back = #000000
color_faded = #94a3b8
color_status = #94a3b8
color_accent = #0000ff
color_warn = #ef4444
color_listitem_back = #000000
color_listitem_title = #ffffff
color_listitem_desc = #e2e8f0
color_listitem_tips = #94a3b8
color_listitem_selected_back = #0f172a
color_listitem_selected_title = #ffffff
color_listitem_selected_desc = #e2e8f0
color_listitem_selected_tips = #94a3b8
font_face = "Sarasa Term SC Nerd"
mono_font_face = "Sarasa Term SC Nerd"
font_large_size = 10
font_large_style = bold
font_snormal_size = 10
font_snormal_style = cleartype
font_normal_size = 10
font_normal_style = cleartype
font_small_size = 10
font_small_style = cleartype
compact_results = yes
listitem_title_font = snormal

[theme/VantaNegate]
opacity_back = 100
satellite_show = never
satellite_pos = topleft
satellite_size = small
control_margin = 3
textbox_padding = 3
listitem_padding = 1
layout = list_selmark,list_icon
color_background = #f8fafc
color_foreground = #0f172a
color_title = #0f172a
color_textbox_back = #ffffff
color_faded = #64748b
color_status = #64748b
color_accent = #0000ff
color_warn = #ef4444
color_listitem_back = #ffffff
color_listitem_title = #1e293b
color_listitem_desc = #334155
color_listitem_tips = #64748b
color_listitem_selected_back = #e2e8f0
color_listitem_selected_title = #1e293b
color_listitem_selected_desc = #334155
color_listitem_selected_tips = #64748b
font_face = "Sarasa Term SC Nerd"
mono_font_face = "Sarasa Term SC Nerd"
font_large_size = 10
font_large_style = bold
font_snormal_size = 10
font_snormal_style = cleartype
font_normal_size = 10
font_normal_style = cleartype
font_small_size = 10
font_small_style = cleartype
compact_results = yes
listitem_title_font = snormal
