[main]
docset_path = "${env:USERHOME}\Local\Data\zeal"
# results = 50
# wildcard = no

# Get the `CFBundleIdentifier` value liked `python` from `Document.docset\Contents\Info.plist`.
# If you cannot search, it may be a problem with the document.
[docs]
tex = latex
lua = lua
love = love2d
py = python
bs = bs4
req = requests
gdt = godot
# rpy = renpy

# See https://kapeli.com/docsets#supportedentrytypes
[types]
a = Attribute
c = Class
e = Exception
f = Function
g = Guide
m = Method
s = Section
v = Variable
o = Option